sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.3
  - jruby-19mode

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "bundle exec rake test_with_coveralls"
